### ISSUE TITLE
Website points to old rc3 github repo: Electric-Coin-Company/zcash

### ISSUE THREAD

**Issue by jonathancross** [Electric-Coin-Company/website#2]
https://github.com/Electric-Coin-Company/website/blob/master/www/index.html#L46

**Comment by jonathancross** [comment]
Someone fixed it, now points to zcash/zcash
Nothing changed there though...

**Comment by daira** [comment]
Pay no attention to the Electric-Coin-Company/zcash fork on github. I'll delete it later (when we're not in the middle of a release :-)
